logging:
  level:
    io.zenwave360.example: DEBUG
#    org.springframework.cloud.stream: DEBUG
#    org.apache.kafka: DEBUG
spring:
  security:
    user:
      name: user
      password: password
      roles: USER
  data:
    mongodb:
      database: zenwave360-example
#      uri: mongodb://localhost:27017,localhost:27018,localhost:27019/zenwave360-example?replicaSet=dbrs
  kafka:
    bootstrap-servers: localhost:9092
  cloud:
    stream:
      function:
        definition: do-customer-request;on-customer-event;on-customer-order-event
      bindings:
        do-customer-request-in-0:
          group: zenwave360-example
          destination: customer.requests
          contentType: application/json
        on-customer-event-out-0:
          group: zenwave360-example
          destination: customer.events
          content-type: application/json
        on-customer-order-event-out-0:
          group: zenwave360-example
          destination: customer-order.events
          content-type: application/json
        on-customer-event-in-0:
          group: zenwave360-example
          destination: customer.events
          content-type: application/json
          dead-letter-queue-error-map: >
            {
              'javax.validation.ValidationException': 'on-customer-event-validation-error-out-0',
              'java.lang.Exception': 'on-customer-event-error-out-0'
            }
        on-customer-order-event-in-0:
          group: zenwave360-example
          destination: customer-order.events
          content-type: application/json
          dead-letter-queue-error-map: >
            {
              'javax.validation.ValidationException': 'on-customer-event-validation-error-out-0',
              'java.lang.Exception': 'on-customer-event-error-out-0'
            }
      kafka:
        bindings:
          on-customer-event-out-0:
            producer:
              configuration:
                key.serializer: org.apache.kafka.common.serialization.StringSerializer
#                schema.registry.url: http://localhost:8081
          on-customer-order-event-out-0:
            producer:
              configuration:
                key.serializer: org.apache.kafka.common.serialization.StringSerializer
#                schema.registry.url: http://localhost:8081
